### ISSUE TITLE
Guard watching .xnode files.

### ISSUE THREAD

**Issue by huba** [ioquatix/utopia#10]
It's a bit annoying when guard restarts puma every time I save a change to a file in pages/. I get 2 system notifications pop up every time I save. Could it be enough to only watch controller.rb files in pages/?

**Comment by ioquatix** [comment]
I understand your pain.

I've raised this issue here https://github.com/puma/puma/issues/1250 and here https://github.com/jc00ke/guard-puma/issues/24

I'd like to see this improved if possible.

I've actually been thinking of making my own web server with the new async gem I've been working on, just for fun/enjoyment. If I did that, it would become the default server and we wouldn't suffer so much.

The .xnode files are also cached by `Utopia::Content` so if they change the server does need to be restarted, unfortunately.

Sorry, I didn't really provide a good answer, but yes, it's a problem.

**Comment by huba** [comment]
Does `Utopia::Content` have to cache when `RACK_ENV` is `:development`?

**Comment by ioquatix** [comment]
I decided that having internal machinery reconfigure itself based on ENV was a bad design, so by default Utopia middleware always operates in what was known as production mode, but is restarted after any file is changed. It makes the most sense and works even if changes in `lib/`.

**Comment by huba** [comment]
So `/lib` is not an appropriate place to put sass source files. :laughing:

**Comment by ioquatix** [comment]
It's not so bad, because keep in mind that those might be cached until the server is restarted.

With Utopia 2.x I took the attitude that things in development should not be so different from in production. Otherwise, you might have bugs which aren't detected until production. The only difference, is that in development, after each change to the source code the server restarts. It's the best approach, but making the server fast to restart is also a high priority.

**Comment by huba** [comment]
What I was actually looking for is [this](https://github.com/guard/guard/wiki/Guardfile-DSL---Configuring-Guard#notification).
My screen kept getting flooded with notification popups from my libnotify frontend. I'll make a PR in a minute.

**Comment by huba** [comment]
Should be fixed with #12
